name: release-common
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run : npm i npm-cli-login
      - run: npm install
      - run: npm run build
      - run: npm version patch
#       - run: npm publish
